site_name: Kira Lempereur's Technical Writing & Technical Marketing Portfolio
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Kantumruy Pro
    code: Fragment Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: teal

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: green

nav:
  - Home: 'index.md'
  - Technical Writing:
    - My Tech Writing Experience: 'tech-writing.md'
    - Product Documentation: 'product-docs.md'
    - API Documentation: 'api-docs.md'
  - Technical Marketing:
    - My Tech Marketing Experience: 'tech-marketing.md'
    - DataDome Global Bot Security Report: 'dd-global-bot-report.md'
    - DataDome Tech Marketing Content: 'dd-content.md'
  - Material Examples:
    - Code Examples: 'code-examples.md'
    - Content Tabs: 'content-tabs.md'
    - Admonitions: 'admonitions.md'
    - Diagrams: 'diagram-examples.md'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KiraLLempereur
      name: Kira Lempereur on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kira-john
      name: Kira Lempereur on LinkedIn

copyright: Copyright &copy; 2024 Kira Lempereur